backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: aaaaa
    label_singular: "Page"
    folder: _pages
    create: true
    nested: { depth: 100, subfolders: false }
    fields:
      - { name: "title", label: "bbbbb", widget: "string" }
      - { name: "date", label: "ccccc", widget: "datetime" }
      - { name: "rating", label: "ddddd", widget: "number" }
      - { name: "body", label: "eeeee", widget: "markdown" }
    meta: { path: { widget: string, label: "zzzzz", index_file: "index" } }

  # - name: docs
  #   label: Dokümanlar 1
  #   label_singular: "Doc"
  #   folder: docs
  #   create: true
  #   nested:
  #     depth: 5
  #     summary: "{{title}}"
  #   fields:
  #     - label: Başlık
  #       name: title
  #       widget: string
  #     - label: İçerik
  #       name: body
  #       widget: markdown
  #   meta: { path: { widget: string, label: "Path", index_file: "index" } }
