backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
# media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
# public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
media_folder: static/img
public_folder: /img

collections:
  - name: "blog" # Rotalarda kullanılan gönderi türü tanımlayıcısı. Benzersiz olmalıdır. ==> /admin/collections/blog
    label: "Blog" # Admin arayüzünün gönderi türüne verdiği ad.
    folder: "_posts/blog" # Bu türdeki dosyaların depo köküne göre nerede saklandığı. ==> -posts/blog/...md ==> Kök dizin içerisindeki yol
    create: true # Kullanıcıların bu koleksiyonda yeni dosyalar oluşturmasına izin vermek için ayarlanır.
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Dosya adı şablonu. Örnek: 2024-06-07-baslik.md şeklinde oluşturur.
    fields: # Burada listelenen alanlar içerik düzenleyicide alanlar olarak gösterilir, ardından belgenin başında ön madde olarak kaydedilir ( Body hariç ).
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" } # Düzenleme alanındaki başlık girilen kısmı
      - { label: "Publish Date", name: "date", widget: "datetime" } # Düzenleme alanındaki tarih seçimi kısmı
      - { label: "Featured Image", name: "thumbnail", widget: "image" } # Düzenleme alanındaki fotoğraf yükleme kısmı
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" } # Düzenleme alanındaki puanlama kısmı
      - { label: "Body", name: "body", widget: "markdown" } # Düzenleme alanındaki body kısmı burada markdown yerleştirilmiş

  - name: "blog2"
    name: "Blog2"
    folder: "_posts2/blog2"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

# backend:
#   name: git-gateway
#   branch: main

# media_folder: static/img
# public_folder: /img

# collections:
#   - name: "docs"
#     label: "Dokümanlar"
#     folder: "docs"
#     create: true
#     nested:
#       depth: 4
#     fields:
#       - {label: "Başlık", name: "title", widget: "string"}
#       - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
#       - {label: "İçerik", name: "body", widget: "markdown"}
#       - {label: "Sıralama", name: "sidebar_position", widget: "number"}
