backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: authors
    label: Yazarlar
    folder: _authors
    create: true
    fields:
      - { name: "name", label: "Ad", widget: "string" }
      - { name: "surname", label: "Soyad", widget: "string" }
      - { name: "email", label: "E-Posta", widget: "string" }
      - { name: "image", label: "Fotoğraf", widget: "image", required: false }

  - name: job_titles
    label: Ünvanlar
    folder: _job_titles
    create: true
    fields:
      - { name: "title", label: "Ünvan Adı", widget: "string" }
      - { name: "description", label: "Ünvan Açıklaması", widget: "text", required: false }

  - name: documents
    label: Dokümanlar
    label_singular: "Doküman"
    folder: docs
    create: true
    nested: { depth: 100, subfolders: false }
    fields:
      - {
          name: "author",
          label: "Yazar",
          widget: "relation",
          collection: "authors",
          search_fields: ["name", "surname"],
          value_field: "email",
          display_fields: ["name", "surname"],
          required: false,
          hint: "Seçim zorunlu değildir."
        }

      - {
          name: "job_titles",
          label: "Ünvan",
          widget: "relation",
          collection: "job_titles",
          search_fields: ["title"],
          value_field: "title",
          display_fields: ["title"],
          required: false,
          hint: "Seçim zorunlu değildir."
        }

      - {
          name: "publish_date",
          label: "Yayın Tarihi",
          widget: "datetime",
          required: false,
          hint: "Zorunlu değildir."
        }

      - {
          name: "title",
          label: "Başlık",
          widget: "string",
          required: false,
          hint: "Zorunlu değildir."
        }

      - {
          name: "summary",
          label: "Özet",
          widget: "text",
          required: false,
          hint: "Zorunlu değildir."
        }

      - {
          name: "tags",
          label: "Etiketler",
          widget: "list",
          max: 5,
          min: 0,
          allow_add: true,
          required: false,
          hint: "Zorunlu değildir."
        }

      - {
          name: "thumbnail",
          label: "Kapak Görseli",
          widget: "image",
          required: false,
          hint: "Zorunlu değildir."
        }

      - {
          name: "body",
          label: "İçerik",
          widget: "markdown",
          required: false,
          hint: "Zorunlu değildir."
        }

    meta: { path: { widget: string, label: "Yol", index_file: "index" } }

  - name: examples
    label: Örnekler
    label_singular: "Example"
    folder: _examples
    create: true
    nested: { depth: 100, subfolders: false }
    fields:
      - {
          # Evet/Hayır, Açık/Kapalı gibi iki durumlu seçimler için kullanılır. => Mesela bir içeriğin aktif/pasif, öne çıkarılmış/çıkarılmamış gibi durumlarını yönetebilmek için kullanılabilir.
          name: "active",
          label: "Aktif mi?",
          widget: "boolean",
          default: true,
          required: false,
        }

      - {
          # Kod blokları eklemek için kullanılır. => Mesela kullanıcıdan bir kod parçası (ör. HTML, CSS, JS) alınacaksa kullanılabilir.
          name: "code",
          label: "Kod",
          widget: "code",
          default_language: "javascript",
          required: false,
        }

      - {
          # Kullanıcıya renk seçici sunar. Kullanıcının seçtiği renk md dosyasına yazlır. İstersek bu rengi herhangi bir md elementine işleyebiliriz. => Mesela kullanıcıdan h1, h2, h3... her biri için ayrı ayrı renk istenebilir.
          name: "color",
          label: "Renk",
          widget: "color",
          required: false,
        }

      - {
          # Tarih ve saat seçici sunar. => Mesela yayın tarihi, etkinlik zamanı gibi zaman bilgisinin gerektiği durumlarda kullanılabilir.
          name: "publish_date",
          label: "Yayın Tarihi",
          widget: "datetime",
          required: false,
        }

      - {
          # Herhangi bir dosya yüklemek için kullanılır. => PDF, doküman, sunum gibi dosyalar eklenmek istendiğinde kullanılabilir.
          name: "document",
          label: "Belge",
          widget: "file",
          required: false,
        }

      - {
          # Her oluşturulan içerikte, belirttiğin sabit bir değeri otomatik olarak dosyanın başına (front matter) ekler. Kullanıcıya admin panelinde hiç gösterilmez.
          name: "layout",
          label: "Layout",
          widget: "hidden",
          default: "blog",
          required: false,
        }

      - {
          # Görsel yüklemek için kullanılır. => Mesela kapak görseli, profil fotoğrafı gibi görsel eklenmesi gereken durumlarda kullanılabilir.
          name: "thumbnail",
          label: "Kapak Görseli",
          widget: "image",
          required: false,
        }

      - {
          # Mesela etiketler, anahtar kelimeler, maddeler gibi birden fazla veri girilecekse kullanılabilir.
          name: "tags",
          label: "Etiketler",
          widget: "list",
          max: 3,
          min: 0,
          allow_add: true,
          required: false,
        }

      - {
          # Harita üzerinden konum seçmek için kullanılır. => Mesela adres, etkinlik yeri, mağaza konumu gibi coğrafi bilgi gerektiğinde kullanılabilir.
          name: "location",
          label: "Konum",
          widget: "map",
          required: false,
        }

      - {
          # Zengin metin (başlık, liste, link, görsel vb.) girişi için kullanılır.
          name: "body",
          label: "İçerik",
          widget: "markdown",
          required: false,
        }

      - {
          # Sayı girişi için kullanılır. => Sıralama, puan, fiyat gibi sayısal veri gerektiğinde kullanılabilir.
          name: "rating",
          label: "Puan",
          widget: "number",
          required: false,
        }

        # Birden fazla alanı bir arada gruplamak için kullanılır. => Mesela adres, sosyal medya linkleri gibi birden fazla alt alanı olan veri gruplarında kullanılabilir.
      - label: "Adres"
        name: "address"
        widget: "object"
        required: false
        fields:
          - { label: "Şehirss", name: "city", widget: "string", required: false }
          - { label: "Posta Kodu", name: "zip", widget: "string", required: false }

      - {
          # Bir içeriği başka bir koleksiyondaki bir veya birden fazla öğeyle ilişkilendirmek için kullanılır. => Bir blog yazısının yazarını seçmek, bir ürünün kategorisini belirlemek için kullanılabilir.
          # Blog yazısına yazar atamak, ürüne kategori atamak, etkinliğe konuşmacı eklemek, referans, kaynak, bağlantı gibi ilişkili veri göstermek
          name: "author",
          label: "Yazar",
          widget: "relation",
          collection: "authors",
          search_fields: ["name"],
          value_field: "name",
          display_fields: ["name"],
          required: false,
        }

      - {
          # Açılır menüden tek veya çoklu seçim için kullanılır. => Mesela kategori, durum, tür gibi önceden tanımlı seçenekler arasından seçim yapılacaksa kullanılabilir.
          name: "category",
          label: "Kategori",
          widget: "select",
          options: ["Duyuru", "Blog", "Etkinlik"],
          required: false,
        }

      - {
          # Tek satırlık metin girişi için kullanılır. => Mesela başlık, isim, kısa açıklama gibi kısa metinler için kullanılabilir.
          name: "title",
          label: "Başlık",
          widget: "string",
          required: false,
        }

      - {
          # Çok satırlı metin girişi için kullanılır. Mesela uzun açıklama, özet, biyografi gibi alanlarda kullanılabilir.
          name: "summary",
          label: "Özet",
          widget: "text",
          required: false,
        }

    meta: { path: { widget: string, label: "Yol", index_file: "index" } }

  - name: documents2
    label: Dokümanlar2
    label_singular: "Doküman2"
    folder: docs2
    create: true
    nested:
      depth: 100
      summary: '{{title}}'
      path:
        - label: 'Kategori'
          index_file: 'index'
        - label: 'Alt Kategori'
          index_file: 'index'
        - label: 'Başlık'
    fields:
      - { name: "email", label: "E-Posta", widget: "string" }

  - name: documents3
    label: Dokümanlar3
    label_singular: "Doküman3"
    folder: docs3
    create: true
    nested:
      depth: 5  # Maksimum 5 seviye derinlik
      summary: '{{title}}'
      path:
        - label: 'Seviye 1'
          index_file: '_index'
        - label: 'Seviye 2'
          index_file: '_index'
        - label: 'Seviye 3'
          index_file: '_index'
        - label: 'Seviye 4'
          index_file: '_index'
        - label: 'Seviye 5'
          index_file: '_index'
          final: true
    fields:
      - { name: "email", label: "E-Posta", widget: "string" }  # 5. seviyede sadece dosya oluşturulabilir, yeni klasör oluşturulamaz