backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: aaaaa
    label_singular: "Page"
    folder: _pages
    create: true
    nested: { depth: 100, subfolders: false }
    fields:
      - { name: "title", label: "bbbbb", widget: "string", required: true }
      - { name: "date", label: "ccccc", widget: "datetime", required: false }
      - { name: "rating", label: "ddddd", widget: "number", required: false }
      - { name: "thumbnail", label: "eeeee", widget: "image", required: false }
      - { name: "body", label: "fffff", widget: "markdown", required: false }
    meta: { path: { widget: string, label: "zzzzz", index_file: "index" } }

  - name: examples
    label: Örnekler
    label_singular: "Example"
    folder: _examples
    create: true
    nested: { depth: 100, subfolders: false }
    fields:
      - { name: "active", label: "Aktif mi?", widget: "boolean", default: true } # Evet/Hayır, Açık/Kapalı gibi iki durumlu seçimler için kullanılır. => Mesela bir içeriğin aktif/pasif, öne çıkarılmış/çıkarılmamış gibi durumlarını yönetebilmek için kullanılabilir.
      - { name: "code", label: "Kod", widget: "code", default_language: "javascript" } # Kod blokları eklemek için kullanılır. => Mesela kullanıcıdan bir kod parçası (ör. HTML, CSS, JS) alınacaksa kullanılabilir.
      - { name: "color", label: "Renk", widget: "color" } # Kullanıcıya renk seçici sunar. Kullanıcının seçtiği renk md dosyasına yazlır. İstersek bu rengi herhangi bir md elementine işleyebiliriz. => Mesela kullanıcıdan h1, h2, h3... her biri için ayrı ayrı renk istenebilir.
      - { name: "publish_date", label: "Yayın Tarihi", widget: "datetime" } # Tarih ve saat seçici sunar. => Mesela yayın tarihi, etkinlik zamanı gibi zaman bilgisinin gerektiği durumlarda kullanılabilir.
      - { name: "document", label: "Belge", widget: "file" } # Herhangi bir dosya yüklemek için kullanılır. => PDF, doküman, sunum gibi dosyalar eklenmek istendiğinde kullanılabilir.
      - { name: "layout", label: "Layout", widget: "hidden", default: "blog" }
      - { name: "thumbnail", label: "Kapak Görseli", widget: "image" } # Görsel yüklemek için kullanılır. => Mesela kapak görseli, profil fotoğrafı gibi görsel eklenmesi gereken durumlarda kullanılabilir.
      - { name: "tags", label: "Etiketler", widget: "list", allow_add: true } # Etiketler, anahtar kelimeler, maddeler gibi birden fazla veri girilecekse kullanılabilir.
      - { name: "location", label: "Konum", widget: "map" }
      - { name: "body", label: "İçerik", widget: "markdown" }
      - { name: "rating", label: "Puan", widget: "number" }
      - label: "Adres"
        name: "address"
        widget: "object"
        fields:
          - { label: "Şehir", name: "city", widget: "string" }
          - { label: "Posta Kodu", name: "zip", widget: "string" }
      - { name: "author", label: "Yazar", widget: "relation", collection: "authors", search_fields: ["name"], value_field: "name", display_fields: ["name"] }
      - { name: "category", label: "Kategori", widget: "select", options: ["Duyuru", "Blog", "Etkinlik"] }
      - { name: "title", label: "Başlık", widget: "string" }
      - { name: "summary", label: "Özet", widget: "text" }
    meta: { path: { widget: string, label: "Yol", index_file: "index" } }

  # - name: docs
  #   label: Dokümanlar 1
  #   label_singular: "Doc"
  #   folder: docs
  #   create: true
  #   nested:
  #     depth: 5
  #     summary: "{{title}}"
  #   fields:
  #     - label: Başlık
  #       name: title
  #       widget: string
  #     - label: İçerik
  #       name: body
  #       widget: markdown
  #   meta: { path: { widget: string, label: "Path", index_file: "index" } }
